bibleweb/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  get 'welcome/about'
  get 'welcome/read'
  get 'welcome/chapter/:ver/:short/:chapter' => 'welcome#chapter'

  root 'welcome#index'

  resources :suggestions

end

bibleweb/app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
end

bibleweb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bibleweb/app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  CSTATUS_NOT_CHECK = 'checking'
  CSTATUS_CHECK_APPROVED = 'approved'
  CSTATUS_NOT_APPROVED = 'checked but not approved'
  def new
  end
  def create
    @suggestion = Suggestion.new(suggestion_params)
    @suggestion.update(check_status: CSTATUS_NOT_CHECK)
    @suggestion.save
      redirect_to @suggestion
  end
  def show
    @suggestion = Suggestion.find(params[:id])
  end
  private
  def suggestion_params
    params.require(:suggestion).permit(:summary, :email, :describe)
  end
end

bibleweb/app/controllers/welcome_controller.rb
require 'net/http'
require 'json'
class WelcomeController < ApplicationController
  def index
  end
  def read
  end
  def chapter
    ver = params[:ver]
    short = params[:short]
    chapter = params[:chapter]
    url = URI.parse('https://www.bible.com/zh-CN/bible/'+ ver +'/' + short + '.' + chapter + '.json')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port, :use_ssl => url.scheme == 'https') {|http|
      http.request(req)
    }
    body = JSON.parse(res.body)
    reader_html = body['reader_html']
    render inline: reader_html
  end
end

bibleweb/app/helpers/application_helper.rb
module ApplicationHelper
end

bibleweb/app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

bibleweb/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bibleweb/app/views/common/_footer.html.erb
<footer class="navbar navbar-default" style="background-color:#2C2D48; color:white; height: 80px">
  <div class="container" style="margin-top:30px">
    <p class="text-center">
      Copyright ©2015 biblesl.com
    </p>
  </div>
</footer>

bibleweb/app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- brand -->
    <div class="navbar-header">
      <%= link_to image_tag("logo.jpeg", :alt => "Brand", :style => "max-width:60px;"), root_path, :class => "navbar-brand" %>
      <!--
      <a class="navbar-brand" href="#">
	<%= image_tag("logo.jpeg", :alt => "Brand", :style => "max-width:60px;") %>
      </a>
      -->
      <button type="button" class="navbar-toggle" data-toggle="collapse"
	      data-target="#bs-example-navbar-collapse-1">
	<span class="sr-only">切换导航</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
    </div>

    <!-- right link-->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	<li> <%= link_to "About", welcome_about_path, :class => "about-li nav-li" %></li>
	<!-- <li> <a class="support-li nav-li" href="#support">Support</a></li> -->
	<li> <%= link_to "Suggest", new_suggestion_path, :class => "suggest-li nav-li" %></li>
      </ul>
    </div>

  </div>
</nav>

bibleweb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bibleweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

bibleweb/app/views/layouts/suggestions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>biblesl.com</title>
    <%= stylesheet_link_tag 'http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js', 'http://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
    <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui">
  </head>
  <body>
    <%= yield %>
  </body>
  </html>

bibleweb/app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>biblesl.com</title>
    <%= stylesheet_link_tag 'http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css', 'welcome'%>
    <%= javascript_include_tag 'http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js', 'http://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js', 'read.js' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui">
  </head>
  <body>
    <%= render "common/navbar" %>
    <%= yield %>
    <%= render "common/footer" %>
  </body>
</html>

bibleweb/app/views/suggestions/new.html.erb
<div class="container-fluid">
  <div class="page-header">
    <h1>我们需要您的建议 <small>我们会尽全力查看每一条建议</small></h1>
  </div>

  <%= form_for :suggestion, url: suggestions_path do |f| %>
  <!--
      <p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
      </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  -->
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1">概要*</span>
    <%= f.text_field :summary, :class => "form-control", :placeholder => "Enter Summary" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon2">邮箱*</span>
    <%= f.email_field :email, :class => "form-control", :placeholder => "Enter Email" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">详细描述</span>
    <%= f.text_area :describe, :class => "form-control" %>
  </div>
  
  <p>
    <%= f.submit :value => '提交' %>
  </p>
<% end %>
</div>

bibleweb/app/views/suggestions/show.html.erb
<div class="container-fluid">
<div class="panel panel-success">
  <div class="panel-body">
    <%= @suggestion.summary %>
    <br />
    <%= @suggestion.describe %>
  </div>
  <div class="panel-footer">
    <%= @suggestion.email %>
  </div>
</div>
</div>

bibleweb/app/views/welcome/about.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1>关于我们</h1>
    <p>实实在在的说，我现在还不知道怎么介绍我们自己，我是个想要做个软件帮助大家更好的去过信仰生活的基督徒</p>
    <p>不久的将来，我会做个完整的wiki和Q&A 来帮助大家了解我们</p>
  </div>
</div>

bibleweb/app/views/welcome/index.html.erb
<div class="container-fluid">
<div class="jumbotron">
  <h1>打造围绕圣经而活的工具</h1>
  <p>他喜爱的是耶和华的律法，他昼夜默诵的也是耶和华的律法。(诗篇1:2 cnvs)</p>
  <p><%= link_to "Try it now", welcome_read_path, :class => "btn btn-primary btn-lg" %></p>
</div>
</div>

<div class="container-fluid">
  <div class="row">
    
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail">
	<img src="todo.jpg" alt="todo">
	<div class="caption">
	  <h3>feature 1</h3>
	  <p>feature info</p>
	  <p><a href="#" class="btn btn-primary" role="button">Button</a></p>
	</div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail">
	<img src="todo.jpg" alt="todo">
	<div class="caption">
	  <h3>feature 2</h3>
	  <p>feature info</p>
	  <p><a href="#" class="btn btn-primary" role="button">Button</a></p>
	</div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail">
	<img src="todo.jpg" alt="todo">
	<div class="caption">
	  <h3>feature 3</h3>
	  <p>feature info</p>
	  <p><a href="#" class="btn btn-primary" role="button">Button</a></p>
	</div>
      </div>
    </div>

  </div>
</div>

<!-- 每日经文 -->
<div class="container-fluid">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">每日经文</h3>
    </div>
    <div class="panel-body">
      平安的路，他们未曾知道；（罗马书3:17）
    </div>
  </div>
</div>

<!-- 每日推荐 -->
<div class="container-fluid">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">推荐</h3>
    </div>
    <div class="panel-body">
      some words
    </div>
  </div>
</div>

bibleweb/app/views/welcome/read.html.erb
<div class="container-fluid">
  <div class="col-xs-0 col-md-4"></div>
  <div class="wrapper col-xs-12 col-md-4 text-center">
    <div class="btn-group" role="group" aria-label="...">
    <!-- version button -->  
    <div class="btn-group" role="group" id="version-menu">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	Version
	<span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
      </ul>
    </div>
    <!-- volumn menu -->
    <div class="btn-group" role="group" id="volumn-menu">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	Volumn
	<span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
      </ul>
    </div>
    <!-- chapter menu-->
    <div class="btn-group" role="group" id="chapter-menu">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	Chapter
	<span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
      </ul>
    </div>
  </div>
  </div>
  
  <div class="col-xs-0 col-md-4"></div>
</div>

<div class="container-fluid">
<div class="col-xs-0 col-md-2"></div>
<div class="container-fluid col-xs-12 col-md-8" id="content-id"></div>
<div class="col-xs-0 col-md-2"></div>
</div>

<div style="height:20px;"></div>